const ActionType = {
  SEARCH_SURAH: 'SEARCH_SURAH',
  SEARCH_MUROTTAL: 'SEARCH_MUROTTAL',
  SELECT_DISPLAY: 'SELECT_DISPLAY',
  SELECT_QARI: 'SELECT_QARI',
  NEXT_MUROTTAL: 'NEXT_MUROTTAL',
  PREV_MUROTTAL: 'PREV_MUROTTAL',
  AUTO_PLAY: 'AUTO_PLAY',
};

export default ActionType;
